### PR TITLE
File Info Format Updated

### PR DESCRIPTION
**Pull request by dhruv2601**
screenshot_2016-10-04-02-21-23_me kartikarora transfersh

It is in response to [this issue](https://github.com/kartikarora/Transfer.sh/issues/3).
This is how it look now!!

### CODE REVIEW

**Review by kartikarora — CHANGES_REQUESTED** [review]
I would like the UI and UX to follow the material design guidelines. If you could make some changes to the current PR, that would be great.

**Comment by kartikarora** [comment]
I'm keeping the PR open for now.

**Comment by dhruv2601** [comment]
Can you suggest some changes you would like to see here, it would be easier that way.

**Comment by kartikarora** [comment]
Anything which follows the material design spec. Like bottom sheets or shared element transition to a new activity!

**Comment by kartikarora** [comment]
@dhruv2601 Are you considering to work on this?

**Comment by kartikarora** [comment]
Closing because of no activity

**Pull request closed without merging**
